export const DARK_THEME = 'DARK_THEME';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FILTERED_LIST = 'FILTERED_LIST';
export const ERROR_API = 'ERROR_API';
